config/routes.rb
Rails.application.routes.draw do

  resources :activities
  resources :movies, only: [:index, :show] do
    resources :comments, only: [:create]
    resources :reviews, only: [:create]
    resources :watchlists, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :reviews, only: [:destroy, :edit, :update] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy, :edit, :update] do
    resources :comments, only: [:create]
  end

  get 'search', to: "movies#search"

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users, only: [:show]
  # get 'users', :to => 'users#show', :as => :user_root

  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, :user, :commentable, { presence: true }
  validate :is_nested_one_deep
  has_many :comments, as: :commentable
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  def is_nested_one_deep
    if !(self.commentable.is_a?(Movie) || self.commentable.is_a?(Review) || self.commentable.commentable.is_a?(Movie))
      self.errors.add("Cannot nest comments more than one level deep.")
    end
  end

  def find_closest_movie_id
    if self.commentable.is_a?(Movie)
      return self.commentable_id
    elsif self.commentable.is_a?(Review)
      return self.commentable.movie.id
    else
      self.commentable.find_closest_movie_id
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    if current_user
      @commentable = find_commentable
      @comment = @commentable.comments.build(comment_params)
      @comment.user = current_user
      track_activity @comment
      respond_to do |format|
        if @comment.save
          format.html {redirect_to :back}
          format.js
        else
          format.html {redirect_to :back}
        end
      end
      #error handling?
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @comment = Comment.find_by(id: params[:id])
    @comment.destroy if @comment.user == current_user
    redirect_to :back
  end

  def edit
    @comment = Comment.find_by(id: params[:id])
    if @comment && @comment.user == current_user
      render 'edit'
    else
      redirect_to :back
    end
  end

  def update
    @comment = Comment.find_by(id: params[:id])
    if @comment && @comment.user == current_user
      @comment.update_attributes(comment_params)
      @comment.save
      redirect_to movie_path(Movie.find_by(id: @comment.find_closest_movie_id))
    else
      redirect_to :back
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:text)
  end

  def find_commentable
    params.each do |name, value|
      if name =~ /(.+)_id$/
        return $1.classify.constantize.find(value)
      end
    end
    nil
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class='comment'>
  <p><%= comment.text %></p>
  <div class='conversation-footer'>
    <span><%= comment.user.username %></span>
    <span><%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</span>
    <% if comment.user == current_user %>
      <%= link_to 'Delete This', comment_path(comment), method: :delete %>
      <%= link_to 'Edit This', edit_comment_path(comment) %>
    <% end %>
  </div>
  <div class='comment-comments'>
    <% if comment.commentable.is_a?(Movie) %>
      <%= render partial: 'comments/form', locals: { commentable: comment } %>
    <% end %>
    <%= render comment.comments %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class='comment-form'>
  <%= form_for([commentable, Comment.new]) do |f| %>
    <%= f.text_area :text %>
    <%= f.submit %>
  <% end %>
</div>

app/views/comments/create.js.erb
$(".movie-comments-container").append(' <%= j render @comment %>');
$(".new_comment #comment_text").value = "";

app/views/comments/edit.html.erb
<h2>Edit Your Comment</h2>
<div class='comment-form'>
  <%= form_for @comment, url: comment_path(@comment), method: :patch do |f| %>
    <fieldset>
      <%= f.label :text %>
      <%= f.text_area :text, html: { value: @comment.text } %>
    </fieldset>
    <%= f.hidden_field :user_id, html: { value: @comment.user_id } %>
    <%= f.hidden_field :commentable_id, html: { value: @comment.commentable_id } %>
    <%= f.hidden_field :commentable_type, html: { value: @comment.commentable_type } %>
    <%= f.submit %>
  <% end %>
</div>