config/routes.rb
Rails.application.routes.draw do

  resources :activities
  resources :movies, only: [:index, :show] do
    resources :comments, only: [:create]
    resources :reviews, only: [:create]
    resources :watchlists, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :reviews, only: [:destroy, :edit, :update] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy, :edit, :update] do
    resources :comments, only: [:create]
  end

  get 'search', to: "movies#search"

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users, only: [:show]
  # get 'users', :to => 'users#show', :as => :user_root

  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    if current_user
      @movie = Movie.find_by(id: params[:movie_id])
      @review = @movie.reviews.build(review_params)
      @review.user = current_user
      # current_user.activities.create! action: "create", trackable: review
      track_activity @review
      respond_to do |format|
        if @review.save
          format.js {}
          format.html { redirect_to :back }
        else
          format.js { redirect_to :back }
          format.html {redirect_to :back}
        end
      end
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @review = Review.find_by(id: params[:id])
    @review.destroy if @review.user == current_user
    respond_to do |format|
      format.js {}
      format.html { redirect_to :back }
    end
  end

  def edit
    @review = Review.find_by(id: params[:id])
    if @review && @review.user == current_user
      render 'edit'
    else
      redirect_to :back
    end
  end

  def update
    @review = Review.find_by(id: params[:id])
    if @review && @review.user == current_user
      @review.update_attributes(review_params)
      @review.save
      redirect_to movie_path(@review.movie)
    else
      redirect_to :back
    end
  end

  private
  def review_params
    params.require(:review).permit(:rating, :text)
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<div class='review-form'>
  <h4>Add a Review</h4>
  <%= form_for([@movie, Review.new], remote: true) do |f| %>
    <fieldset>
      <%= f.label :rating %>
      <%= f.select(:rating, options_for_select([["🌟", 1],["🌟🌟", 2],["🌟🌟🌟", 3], ["🌟🌟🌟🌟", 4]])) %>
    </fieldset>
    <fieldset>
      <%= f.label :text %>
      <%= f.text_area :text %>
    </fieldset>
    <%= f.submit %>
  <% end %>
</div>

app/views/reviews/_review.html.erb
<div class='review'>
  <h4><%= '🌟' * review.rating %></h4>
  <p><%= review.text %></p>
  <div class='conversation-footer'>
    <span><%= review.user.username %></span>
    <span><%= distance_of_time_in_words(Time.now, review.created_at) %> ago</span>
    <% if review.user == current_user %>
      <%= link_to "Delete This", review_path(review), remote: true, method: :delete %>
      <%= link_to "Edit This", edit_review_path(review) %>
    <% end %>
  </div>
  <div class='review-comments'>
    <%= render partial: 'comments/form', locals: { :commentable => review } %>
    <%= render review.comments %>
  </div>
</div>

app/views/reviews/create.js.erb
$(".reviews-container").append("<%= escape_javascript(render @review) %>");
$(".review-form select").val(1);
$(".review-form textarea").val("");
$(".review-form").hide();

app/views/reviews/destroy.js.erb
$('.review').has('a').remove();
$('.review-form').show();

app/views/reviews/edit.html.erb
<h2>Edit Your Review</h2>
<div class='review-form'>
  <%= form_for @review, url: review_path(@review), method: :patch do |f| %>
    <fieldset>
      <%= f.label :rating %>
      <%= f.select(:rating, options_for_select([["🌟", 1],["🌟🌟", 2],["🌟🌟🌟", 3], ["🌟🌟🌟🌟", 4]])) %>
    </fieldset>
    <fieldset>
      <%= f.label :text %>
      <%= f.text_area :text, html: { value: @review.text } %>
    </fieldset>
    <%= f.hidden_field :user_id, html: { value: @review.user.id } %>
    <%= f.hidden_field :movie_id, html: { value: @review.movie.id } %>
    <%= f.submit %>
  <% end %>
</div>