config/routes.rb
Rails.application.routes.draw do

  resources :activities
  resources :movies, only: [:index, :show] do
    resources :comments, only: [:create]
    resources :reviews, only: [:create]
    resources :watchlists, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  resources :reviews, only: [:destroy, :edit, :update] do
    resources :comments, only: [:create]
  end
  resources :comments, only: [:destroy, :edit, :update] do
    resources :comments, only: [:create]
  end

  get 'search', to: "movies#search"

  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :users, only: [:show]
  # get 'users', :to => 'users#show', :as => :user_root

  root to: 'movies#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImdbClone</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', "https://fonts.googleapis.com/css?family=Ubuntu+Condensed", media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.1/js/materialize.min.js"></script>

  </head>

  <body>
    <header>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <div id='nav-bar'>
        <nav>
          <ul>
            <% if user_signed_in? %>
              <li>
                <%= "Welcome #{current_user.username}" %>
              </li>
              <li>
                <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
              <li>
                <%= link_to('Edit registration', edit_user_registration_path) %>
              </li>
              <li>
                <%= link_to("My Profile", current_user) %>
              </li>
                <% else %>
              <li>
                <%= link_to('Login', new_user_session_path)  %>
              </li>
              <li>
                <%= link_to('Register', new_user_registration_path) %>
              </li>
            <% end %>
          </ul>
        </nav>
      </div>
      <a href="/"><img class="brand-logo" src= "<%= asset_path('IMDB.jpeg') %>" alt="IMDB Logo"></a>
      <div id='search-form'>
        <%= form_tag( movies_path, method: "get", id: "search-form") do %>
          <% end %>
        <%= form_tag search_url, method: "get", id: "search-form" do %>
          <%= text_field_tag :search, params[:search], placeholder: "The Land Before Time" %>
          <%= submit_tag "Search Movies", name: nil %>
        <% end %>
      </div>
    </header>
    <div id='content-wrapper'>
      <%= yield %>
    </div>

  </body>
</html>